# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(help_text='博客内容')),
                ('pub', models.DateTimeField(verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '博客',
                'verbose_name_plural': '博客',
                'ordering': ['-pub'],
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
